### ISSUE TITLE
Feedback Datadashboad

### ISSUE THREAD

**Issue by nerdale** [YocelinGR/cdmx-2018-06-bc-core-am-data-dashboard#21]
Queridas @EstefaniaMolinaa y @YocelinGR 
Estuve revisando el proyecto entregado y tengo algunos comentarios:

1. En realidad no son muchos comentarios porque entregaron un excelente trabajo, asi que mis felicitaciones para ustedes :clap: 

2. Excelente Readme, me paro y las aplaudo, primer readme con el nivel completo que veo, tiene todo lo necesario, una breve introducción al problema, como se usa y/o programa según el tipo de usuario (cliente o desarrollador), documentación general de las funciones, desiciones de diseño, perfecto :smile: mis felicitaciones para ustedes :heart: :heart: :heart: 

3. Excelente uso de eslint, ningún error ni warning :clap: 

4. Si bien los identificadores que usan son bastantes descriptivos tanto en variables como en funciones, hay algunos nombres bastante crípticos como **deepCont** **i** **j**, entiendo que estos últimos dos son contadores, pero para hacerlo más descriptivos puede ser **counterGenerations** **counterStatus** no sé, algo así.

5. Se nota que trabajaron con orientación a test pero que cuando el proyecto creció este se complejizó y el énfasis lo colocaron en otros puntos. Yo sé que en el siguiente proyecto saldrá mejor, van avanzando muy bien :smiley: 

6. Ojo con los archivos html, están llenos de errores como por ejemplo en el **index.html** en las líneas 90, 91 y 92, tienen dos etiquetas de cierre`</html>` eso ya está mal y además no tiene la etiqueta de apertura arriba, eso es un detalle que no se les puede escapar porque es parte esencial de la estructura. En el archivo **iniciosesion.html** mezclan comillas simples con comillas dobles, recuerden que las simples se usan en los archivos Javascript y las dobles en los archivos HTML, esto no tiene que ver con cosa de gustos, sino que con los estándares de google y sus motores de búsqueda. En la línea 17 del archivo de inicio de sesión tienen la siguiente etiqueta `<secction class="row">` está mal escrito, es con una C..**section** no **secction**

7. Ojo con la indentación, si bien no es algo que esté dentro de la rúbrica, si es esencial para el tema del codereview que recibimos, recuerden que los proyectos están alojados en una plataforma abierta como github donde podemos recibir codereview de cualquier desarrollador del mundo :smile: 

8. No sirve de nada crear issues si no va a existir una interacción entre ustedes, lo mismo con los milestones, si solo van a estar creados sin mayor porpósito. Deben trabajar esa parte :heart: 

9. Si bien se nota que trabajaron en base  a un usuario, deben tener en cuenta que la TM de CDMX no era la única usuaria y ustedes hablan especificamente de las necesidades de ella en el readme de ux y por otro lado mencionan las entrevistas pero no hay documentación de ellas, ni de las preguntas ni las respuestas.

10. Tienen jerarquía en los componentes pero a veces se hace inconsistente por ejemplo cuando veo el nombre de la sede más pequeño que la cantidad de alumnas o el tiempo más grande que los temas, hay que revisar el peso e importancia visual de algunos elementos. En cuanto al color y tiopigrafía, si el usuario tiene un manual de marca con estos dos temas definidos deben seguir la misma línea para que sea una extensión del producto principal (en este caso podría ser del LMS).

En general tienen un muy buen proyecto con detalles a mejorar, las aliento a que lo mejoren y que luego intenten hacer el código más eficiente, les será muy útil al momento de crear su portafolio :smile: 
Vamos con todooooo :metal: :rocket:

**Comment by YocelinGR** [comment]
Gracias Alexandra, trabajaremos muy duro en hacer las mejoras necesarias.

**Comment by nerdale** [comment]
Vamos con power :smile: :muscle:
