### ISSUE TITLE
Feedback Sprint 1 Datadashboard

### ISSUE THREAD

**Issue by nerdale** [YocelinGR/cdmx-2018-06-bc-core-am-data-dashboard#4]
Hola @EstefaniaMolinaa y @YocelinGR 
He estado revisando el proyecto y tengo algunos comentarios:

1. Si bien entregan los prototipos de alta fidelidad y baja fidelidad, falta dejar un registro profundo en el readme de toda la investigación de ux que hicieron para llegar a esos resultados. En el boilerplate venía en el readme de **src/ux** todos los tópicos que debían tocar, revisen esos detalles, es ahí donde deberían colocar toda la información.

2.  Cuando en el test dice `debería exponer función computeStudentsStats en objeto global` quiere decir que **computeStudentsStats** es una función, no un método de un objeto data como lo están haciendo en el proyecto, son funciones comúnes y corrientes, así es sucesivamente con todas las otras funciones. (window.computeStudentsStats)

3. Ya logran entrar a un dato, les recomiendo seguir indagando y en honor al deadline del sprint 2 que se viene encima, ponerle mucho énfasis en ya poder obtener los datos que necesito.

4. Recuerden utilizar HTML semántico `<header></header> <section></section> <aside></aside> <footer></footer> <article></article>`

5. Ojo con el trabajo colaborativo, solo hay commits de @YocelinGR 

Vamos con todo chicas! a demostrarle al mundo que pueden ser las mejores desarrolladoras :heart: :metal:

**Comment by YocelinGR** [comment]
A nombre de Yocelin GR y Estefanía Molina hacemos constar que recibimos el issue. Lamentamos mucho no haber respondido antes de acuse de recibido. Saludos

**Comment by nerdale** [comment]
Perfecto, cerraré el issue entonces.
:rocket:
